### ISSUE TITLE
proxy-vole in Maven Central

### ISSUE THREAD

**Issue by lodimas** [volkertb/autoproxy-maven-plugin#3]
proxy-vole is already available in Maven Central. So, it would be a good idea to remove the local repository, and replace the dependency to proxy-vole with that in Maven Central (thus updating it).

I already did this locally, and there are only a few minor trivial refactoring changes needed.

**Comment by volkertb** [comment]
Thanks for pointing this out. I'll be sure to take a look at @MarkusBernhardt's fork. It seems he's been making some nice improvements to it.
